### ISSUE TITLE
[Request] MangaDex API v5 support

### ISSUE THREAD

**Issue by IntermittentlyRupert** [hkalexling/mango-plugins#10]
**Website name and URL**
[MangaDex API v5](https://api.mangadex.org/docs.html)

**Additional context**
MangaDex have brought their v5 API live in read-only mode.

**Comment by IntermittentlyRupert** [comment]
Not sure if this is the correct place for this issue... Please close if I'm wrong!

**Comment by hkalexling** [comment]
Hi, thanks for the reminder! I saw it on Twitter, and I am excited about the new API :D It's okay to open the issue here, though I would have to heavily rewrite the main app to integrate the new API. While I was waiting for them to release the new API, I have been focusing on developing the official React Native app instead of the main app. I guess it is now the time to switch back to the main app.

**Comment by IntermittentlyRupert** [comment]
Not sure how much rework this would involve relative to a straight v2 --> v5 upgrade, but would you consider potentially replacing the built-in Mangadex integration with a more fully-featured plugin API, including search and follows? It'd make the whole thing much less dependent on a single site.

Not sure I'd be much help on the mango internals side of things, but I'd be happy to help build out the plugins for that sort of project.

ETA: [The sources system in Paperback for iOS](https://paperback.moe/help/guides/adding-repos/) is probably the closest example of what I'm thinking.

**Comment by hkalexling** [comment]
Yes that's exactly the plan! See https://github.com/hkalexling/mango-plugins/issues/4#issuecomment-813973013 and https://github.com/hkalexling/Mango/issues/24#issuecomment-806019841

**Comment by Nerothos** [comment]
👌 
Yeah it would be nice to transform the built-in mangadex to a plugin so the base mango app is cleaner

**Comment by GlassedSilver** [comment]
Not sure if this is really relevant, but the MangaDex website has undergone rework of the web UI, so if any parts rely on more than the API I think now could be a good time to check out a more stable state of the website.

**Comment by carks32** [comment]
Hi, I wanted to comment here, is mangadex support going to be happening any time soon? Since you can't just search by ids anymore

**Comment by hkalexling** [comment]
@carks32 It's hard for me to give an ETA because I can only work on this in my very limited spare time. I would say it probably won't be available in the next 1-2 months. In the mean time you can use other open source downloaders to download from MangaDex, or try the tool created by @tr7zw (see https://github.com/hkalexling/Mango/issues/24#issuecomment-947639476)

**Comment by fabiopbx** [comment]
@hkalexling https://github.com/hkalexling/mango-plugins/pull/19 likely closes this unless you wanna take the feature set further, its basic but has download capabilities using the new GUID system v5 uses :) 

its the plugin called 'mangadexV5' :)

**Comment by hkalexling** [comment]
@fabiopbx Ah but the the v2 plugin was first mentioned and discussed here so I wanted to keep this open until the new plugin is available. I think some people are following this thread for that. Thanks for the reminder tho!

**Comment by GlassedSilver** [comment]
@hkalexling You're right on the money with that! :D
