### ISSUE TITLE
[Bug] Error while using Manganelo plugin

### ISSUE THREAD

**Issue by amanagarwal97** [hkalexling/mango-plugins#13]
**Plugin**
Name/ID of the plugin: Manganelo

**Describe the bug**
I get an error while searching through this plugin. It says `TypeError: cannot read property 'id_encode' of undefined`

**To Reproduce**
1. Go to 'Download'
2. Click on 'Plugins'
3. Select Manganelo from dropdown and Enter search text

**Expected behavior**
Searching should work

**Screenshots**

**Mango version**
E.g., v0.21.0

**Additional context**
The problem seems to be with the changes in the manganelo API. In the search response the json field 'id_encode' is not actually the id of the manga but that of the author. So changes might be needed on that.
E.g.
```
{
  "id": "29117",
  "id_encode": "pn918005",
  "name": "<span style=\"color: #FF530D;font-weight: bold;\">solo</span> Leveling",
  "nameunsigned": "pn918005",
  "lastchapter": "Chapter 162",
  "image": "https://avt.mkklcdnv6temp.com/30/a/17-1583496340.jpg",
  "author": "Sung-Lak Jang",
  "link_story": "https://readmanganato.com/manga-dr980474"
}
```

**Comment by hkalexling** [comment]
Thanks for the bug report! According to the error message, we are trying to access the `id_encode` field of something undefined. Specifically, on this line

https://github.com/hkalexling/mango-plugins/blob/8119decdec3c829427fc8b92d2f414020691ad98/plugins/manganelo/index.js#L18

`JSON.parse(search)` is either not an array or is an empty array, and that's why `JSON.parse(search)[0]` is undefined. I think adding a sanity check before accessing `id_encode` should be enough.

I noticed that you forked the repo, so please go ahead if you are willing to submit a PR. I will be happy to help if you have any questions :-)

**Comment by amanagarwal97** [comment]
The reason why `JSON.parse(search)[0]` is undefined is because on hitting that URL we are getting an empty response. Even when i visit manganelo on my browser it redirects me to `https://manganato.com/` and the search url is actually `https://manganato.com/getstorysearchjson` because of this we are getting an empty response.

This issue aside the website url schema has changed a bit and it doesn't follow the same one that you have used in the plugin.
```
Manga URL = https://readmanganato.com/manga-dr980474
Chapter URL = https://readmanganato.com/manga-dr980474/chapter-158
```
The `id_encode` doesn't seem to give you the manga code but rather its there in `link_story`. I have actually got it working somehow but feel like its still a bit messy. I might work on it some more and if its fine with you i can raise a PR.

**Comment by hkalexling** [comment]
Sure please take your time! Appreciate your interest in contributing :)
